rightscale/policies

- shutdown_scheduler.rb
to allow for automated shutdown and termination of instances based on specific tags
> added shutdown_scheduler CAT 

- README.md
- fastly_security_group_rules.cat.rb
Still needs README update, coming next.
> Adding Fastly SG Rules CAT

- instances/instance_runtime_policy/long_running_instances.cat.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/policies/30)
> Psasset 727 issue 28

- CHANGELOG.md
> Week of 11-20-2017 Changelog

- CHANGELOG.md
- README.md
> Release 12-07-2017

- tags/tag_checker_policy/README.md
- tags/tag_checker_policy/changelog.md
- tags/tag_checker_policy/tag_checker.cat.rb
- [x ] New functionality has been documented in the README if applicable
- [ x] New functionality has been documented in CHANGELOG.MD
> adding advanced tag matching

- tags/tag_checker_policy/README.md
- tags/tag_checker_policy/changelog.md
- tags/tag_checker_policy/tag_checker.cat.rb
> update advanced tags to create missing tag

- tags/tag_checker_policy/README.md
- tags/tag_checker_policy/changelog.md
- tags/tag_checker_policy/tag_checker.cat.rb
Fixes #44 
- [x ] New functionality has been documented in the README if applicable
> Allow the user to provide a prefix value for invalid tags values

- CHANGELOG.md
> Week of 01-15-2018 Release

- tags/tag_checker_policy/README.md
- tags/tag_checker_policy/changelog.md
- tags/tag_checker_policy/tag_checker.cat.rb
* remove param_email requirement and use launched by tag to send emails, and append to param_email list.
* Add Delete Resource parameter option if tags missing
> Tag Checker Policy: Add Delete Resource parameter option if tags missing

- tags/tag_checker_policy/README.md
- tags/tag_checker_policy/changelog.md
- tags/tag_checker_policy/tag_checker.cat.rb
Applying the tag policy to Volumes.
resolves #40
> Apply tag policy to Volumes

- tags/tag_checker_policy/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rightscale/policies/65)
> readme update

- CHANGELOG.md
> Release Week of 01/22/2018

- tags/tag_checker_policy/changelog.md
- tags/tag_checker_policy/tag_checker.cat.rb
Adding additional columns to CSV file 
#46
> Adding additional columns to CSV File

- CHANGELOG.md
> Release Week of 01-29-2018

- tags/tag_checker_policy/tag_checker.cat.rb
Additional logging using sys_log
exception handling for @resource.created_at = null 
Error when attempting to add null to a line item in the csv.
exception handling for @resource.created_at = null
> Psasset 819

- instances/instance_runtime_policy/README.md
- instances/instance_runtime_policy/changelog.md
- instances/instance_runtime_policy/long_running_instances.cat.rb
Added CSV export with email and auto Terminate option.
N/A
> Sbarnhart patch1

- instances/instance_runtime_policy/long_running_instances.cat.rb
Swapped updated_at for  created_at when calculating runtime.
> switched updated_at with created_at

- instances/instance_runtime_policy/long_running_instances.cat.rb
skip instances that have been terminated
> adding logic to catch terminated instance

- instances/azure_superseded_instance_types/README.md
- instances/azure_superseded_instance_types/azure_superseded_instance_types.rb
- instances/azure_superseded_instance_types/changelog.md
Initial release of Azure Superseded Instance Types Policy
N/A
> Azure Superseded Instance Types Policy - Initial Release

- README.md
Adding a simple note to start informing users about the new policy mgmt. 
> Adding a note about the new policy management.
